"""add description, weight, temperament to dog

Revision ID: 20a3b8048590
Revises: 7c80391c1f21
Create Date: 2025-11-14 03:22:04.119279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a3b8048590'
down_revision = '7c80391c1f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('temperament', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('temperament')
        batch_op.drop_column('weight')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
