"""add image_url to dogs and api_id to breeds

Revision ID: 7c80391c1f21
Revises: 83f69ac6c298
Create Date: 2025-11-13 15:59:41.913932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c80391c1f21'
down_revision = '83f69ac6c298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['api_id'])

    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###
